/* Offline configuration for CoreApp. This file intentionally has no network dependencies. */
(function (root) {
  'use strict';
  var V=3, RELEASE='0.1.3', MAX=8, MAX_NAME=20, CACHE='locusProfiles.v3', CONFIG='config';
  var K={v:0,type:1,result:4,index:30,count:31,data:32,id:33,release:35};
  var strings={
    en:{title:'Locus Bridge',profiles:'Profiles',theme:'Theme',dark:'Dark',light:'Light',active:'Active',edit:'Edit',copy:'Copy',up:'Move up',down:'Move down',del:'Delete',add:'Add profile',save:'Save',cancel:'Cancel',name:'Display name',mapping:'Locus profile',metrics:'Metrics',addMetric:'Add metric',remove:'Remove',confirm:'Delete this profile?',last:'At least one profile is required.',limit:'A maximum of eight profiles is allowed.',invalid:'Resolve every Locus profile and choose 1–6 unique metrics.',duplicate:'Display names must be unique.',fresh:'Locus profiles updated.',stale:'Using the last saved Locus profile list.',empty:'The bridge responded, but Locus returned no recording profiles.',unavailable:'No profile response received from the bridge yet.',incompatible:'Incompatible bridge/watch version. Install version '+RELEASE+' on both devices.',activity:'Activity',copySuffix:' copy'},
    de:{title:'Locus Bridge',profiles:'Profile',theme:'Darstellung',dark:'Dunkel',light:'Hell',active:'Aktiv',edit:'Bearbeiten',copy:'Kopieren',up:'Nach oben',down:'Nach unten',del:'Löschen',add:'Profil hinzufügen',save:'Speichern',cancel:'Abbrechen',name:'Anzeigename',mapping:'Locus-Profil',metrics:'Messwerte',addMetric:'Messwert hinzufügen',remove:'Entfernen',confirm:'Dieses Profil löschen?',last:'Mindestens ein Profil ist erforderlich.',limit:'Höchstens acht Profile sind möglich.',invalid:'Alle Locus-Profile zuordnen und 1–6 eindeutige Messwerte wählen.',duplicate:'Anzeigenamen müssen eindeutig sein.',fresh:'Locus-Profile aktualisiert.',stale:'Zuletzt gespeicherte Locus-Profile werden verwendet.',empty:'Die Bridge antwortet, aber Locus liefert keine Aufzeichnungsprofile.',unavailable:'Noch keine Profilantwort von der Bridge empfangen.',incompatible:'Bridge und Watch sind inkompatibel. Version '+RELEASE+' auf beiden Geräten installieren.',activity:'Aktivität',copySuffix:' Kopie'}
  };
  var metricNames={en:['Elapsed time','Moving time','Total distance','Moving distance','Current speed','Average speed','Max speed','Current pace','Average pace','Altitude','Ascent','Descent','Vertical speed','Slope','Average heart rate','Max heart rate','Average cadence','Max cadence','Average power','Max power','Energy'],de:['Gesamtzeit','Zeit in Bewegung','Gesamtstrecke','Strecke in Bewegung','Aktuelle Geschwindigkeit','Durchschnittsgeschwindigkeit','Höchstgeschwindigkeit','Aktuelles Tempo','Durchschnittstempo','Höhe','Anstieg','Abstieg','Vertikalgeschwindigkeit','Steigung','Durchschnittspuls','Maximalpuls','Durchschnittliche Trittfrequenz','Maximale Trittfrequenz','Durchschnittsleistung','Maximalleistung','Energie']};
  function locale(value){return String(value||'en').toLowerCase().replace('-','_').split('_')[0]==='de'?'de':'en';}
  function defaultsFor(lang){var de=locale(lang)==='de';return {theme:'dark',selected:0,profiles:[{name:de?'Wandern':'Hiking',locus:de?'Wandern':'Hiking',protected:false,metrics:[1,3,5,6,10,11]},{name:de?'Radfahren':'Cycling',locus:de?'Radfahren':'Cycling',protected:false,metrics:[1,3,5,6,7,11]},{name:de?'Laufen':'Running',locus:de?'Laufen':'Running',protected:false,metrics:[1,3,8,9,15,17]}]};}
  var defaults=defaultsFor('en');
  function clone(x){return JSON.parse(JSON.stringify(x));}
  function validName(x){return typeof x==='string'&&x.trim().length>0&&x.length<=MAX_NAME&&!/[|\r\n]/.test(x);}
  function validLocus(x){return typeof x==='string'&&x.trim().length>0&&!/[|\r\n]/.test(x);}
  function migrate(c){if(!c||!Array.isArray(c.profiles))return c;c.profiles.forEach(function(p){p.protected=false;});return c;}
  function validate(c,locusNames){
    if(!c||(c.theme!=='light'&&c.theme!=='dark')||!Array.isArray(c.profiles)||c.profiles.length<1||c.profiles.length>MAX||c.selected<0||c.selected>=c.profiles.length)return false;
    var names={}; return c.profiles.every(function(p){
      var key=typeof p.name==='string'?p.name.toLowerCase():'';
      if(!validName(p.name)||!validLocus(p.locus)||names[key]||!Array.isArray(p.metrics)||p.metrics.length<1||p.metrics.length>6)return false;
      if(Array.isArray(locusNames)&&!locusNames.some(function(n){return n===p.locus;}))return false;
      names[key]=true;var seen={};return p.metrics.every(function(m){m=Number(m);if(m<1||m>21||m%1||seen[m])return false;seen[m]=1;return true;});
    });
  }
  function serialize(c){if(!validate(c))throw new Error('Invalid configuration');return [c.theme+'|'+c.selected].concat(c.profiles.map(function(p){return [p.name,p.locus,'0',p.metrics.join(',')].join('|');})).join('\n');}
  function parse(s){try{var lines=String(s).split('\n'),h=lines.shift().split('|'),c={theme:h[0],selected:Number(h[1]),profiles:[]};lines.forEach(function(line){var p=line.split('|');c.profiles.push({name:p[0],locus:p[1],protected:false,metrics:p[3].split(',').map(Number)});});return validate(c)?migrate(c):null;}catch(_){return null;}}
  function uniqueName(c,base){var n=String(base).slice(0,MAX_NAME),i=2;while(c.profiles.some(function(p){return p.name.toLowerCase()===n.toLowerCase();})){var s=' '+i++;n=String(base).slice(0,MAX_NAME-s.length)+s;}return n;}
  function add(c,source,lang){if(c.profiles.length>=MAX)return false;var p=clone(source||{name:strings[locale(lang)].activity,locus:'',metrics:[1,3]});p.protected=false;p.name=uniqueName(c,p.name);c.profiles.push(p);return true;}
  function remove(c,i){if(!c.profiles[i]||c.profiles.length===1)return false;var selected=c.profiles[c.selected];c.profiles.splice(i,1);c.selected=Math.max(0,c.profiles.indexOf(selected));if(c.selected<0)c.selected=Math.min(i,c.profiles.length-1);return true;}
  function rename(c,i,name){if(!c.profiles[i]||!validName(name)||c.profiles.some(function(p,j){return j!==i&&p.name.toLowerCase()===name.toLowerCase();}))return false;c.profiles[i].name=name;return true;}
  function move(c,from,to){if(from<0||to<0||from>=c.profiles.length||to>=c.profiles.length)return false;var selected=c.profiles[c.selected],p=c.profiles.splice(from,1)[0];c.profiles.splice(to,0,p);c.selected=c.profiles.indexOf(selected);return true;}
  function chunks(payload,size){var out=[],part='',bytes=0;for(var i=0;i<payload.length;i++){var ch=payload.charAt(i);if(i+1<payload.length&&/^[\uD800-\uDBFF]$/.test(ch)){ch+=payload.charAt(++i);}var n=unescape(encodeURIComponent(ch)).length;if(bytes+n>size&&part){out.push(part);part='';bytes=0;}part+=ch;bytes+=n;}if(part||!out.length)out.push(part);return out;}
  function send(c){var parts=chunks(serialize(c),80),id=Date.now()&0x7fffffff;function next(i){if(i>=parts.length)return;var d={};d[K.v]=V;d[K.release]=RELEASE;d[K.type]=5;d[K.index]=i;d[K.count]=parts.length;d[K.data]=parts[i];d[K.id]=id;Pebble.sendAppMessage(d,function(){next(i+1);},function(){next(i+1);});}next(0);}
  function incoming(p,key,name){return p[key]!==undefined?p[key]:p[name];}
  function Transfer(){this.reset();} Transfer.prototype.reset=function(){this.id=-1;this.count=0;this.parts=[];}; Transfer.prototype.accept=function(p){var id=Number(incoming(p,K.id,'TRANSFER_ID')),index=Number(incoming(p,K.index,'CHUNK_INDEX')),count=Number(incoming(p,K.count,'CHUNK_COUNT')),data=incoming(p,K.data,'CHUNK_DATA');if(typeof data!=='string'||count<1||count>128||index<0||index>=count)return null;if(id!==this.id||count!==this.count){this.id=id;this.count=count;this.parts=[];}if(this.parts[index]!==undefined)return null;this.parts[index]=data;for(var i=0;i<count;i++)if(this.parts[i]===undefined)return null;var value=this.parts.join('');this.reset();return value;};
  function profilePayload(value){if(value==='')return [];var names=value.split('\n');if(names.some(function(n){return !validLocus(n);}))return null;var seen={};return names.filter(function(n){if(seen[n])return false;seen[n]=true;return true;});}
  function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');}
  function page(configuration,locusNames,lang,cacheState){
    lang=locale(lang);var t=strings[lang],state=encodeURIComponent(JSON.stringify(migrate(clone(configuration)))),loc=encodeURIComponent(JSON.stringify(locusNames||[]));
    var html='<!doctype html><html lang="'+lang+'"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+t.title+'</title><style>*{box-sizing:border-box}body{margin:0;background:#eef0f3;color:#202124;font:15px -apple-system,BlinkMacSystemFont,sans-serif}header{position:sticky;top:0;background:#fff;padding:14px 16px;border-bottom:1px solid #ccd0d5;z-index:2}h1{font-size:20px;margin:0}.wrap{padding:10px 12px 78px}.group{background:#fff;border-radius:9px;margin:10px 0;overflow:hidden}.section{padding:7px 12px;color:#687078;font-size:12px;text-transform:uppercase}.row{padding:11px 12px;border-top:1px solid #e5e7e9}.row:first-child{border-top:0}.summary{color:#697078;font-size:13px;margin-top:3px}.actions button{margin:7px 5px 0 0}button,select,input{font:inherit}button{padding:7px 9px;border:1px solid #c6cbd0;border-radius:6px;background:#fff}.primary{background:#157efb;color:#fff;border-color:#157efb}.danger{color:#b3261e}.bar{position:fixed;bottom:0;left:0;right:0;padding:10px 12px;background:#fff;border-top:1px solid #ccd0d5}.bar button{width:100%;padding:11px}.field{display:block;margin:11px 0}.field input,.field select{display:block;width:100%;margin-top:5px;padding:9px}.metric{display:flex;gap:6px;align-items:center;margin:7px 0}.metric select{flex:1;padding:8px}.notice{padding:9px 12px;background:#fff4ce;color:#5d4a00}.hidden{display:none}</style><header><h1>'+t.title+' <small>'+RELEASE+'</small></h1></header><div id="notice" class="notice">'+esc(cacheState==='incompatible'?t.incompatible:cacheState==='fresh'?t.fresh:cacheState==='stale'?t.stale:t.unavailable)+'</div><main class="wrap"><div id="overview"><div class="section">'+t.theme+'</div><div class="group row"><select id="theme"><option value="dark">'+t.dark+'</option><option value="light">'+t.light+'</option></select></div><div class="section">'+t.profiles+'</div><div id="profiles" class="group"></div><button id="add">'+t.add+'</button></div><div id="editor" class="hidden"><div class="group row"><label class="field">'+t.name+'<input id="name" maxlength="20"></label><label class="field">'+t.mapping+'<select id="locus"></select></label><div class="section">'+t.metrics+'</div><div id="metrics"></div><button id="addMetric">'+t.addMetric+'</button></div><button id="editorDone" class="primary">'+t.save+'</button> <button id="editorCancel">'+t.cancel+'</button></div></main><div class="bar"><button id="save" class="primary">'+t.save+'</button></div><script>'+settingsScript(state,loc,lang)+'</script></html>';
    return 'data:text/html;charset=utf-8,'+encodeURIComponent(html);
  }
  function settingsScript(state,loc,lang){
    return 'var c=JSON.parse(decodeURIComponent("'+state+'")),loc=JSON.parse(decodeURIComponent("'+loc+'")),lang="'+lang+'",T='+JSON.stringify(strings[lang])+',MN='+JSON.stringify(metricNames[lang])+',editing=-1,draft=null;'+
    'var q=function(x){return document.getElementById(x)},profiles=q("profiles"),overview=q("overview"),editor=q("editor");q("theme").value=c.theme;'+
    'function closeConfig(x){if(typeof window.__pebbleConfigClose==="function")window.__pebbleConfigClose(x);else location.href="pebblejs://close#"+encodeURIComponent(x)}'+
    'function unique(base){var n=base.slice(0,20),i=2;while(c.profiles.some(function(p){return p.name.toLowerCase()===n.toLowerCase()})){var s=" "+i++;n=base.slice(0,20-s.length)+s}return n}'+
    'function draw(){profiles.innerHTML="";c.profiles.forEach(function(p,i){var r=document.createElement("div");r.className="row";r.innerHTML="<label><input type=radio name=active "+(c.selected===i?"checked":"")+"> "+T.active+"</label><strong> "+safe(p.name)+"</strong><div class=summary>"+safe(p.locus)+" · "+p.metrics.length+"</div><div class=actions><button class=edit>"+T.edit+"</button><button class=copy>"+T.copy+"</button><button class=up>"+T.up+"</button><button class=down>"+T.down+"</button><button class=del>"+T.del+"</button></div>";r.querySelector("[name=active]").onclick=function(){c.selected=i;draw()};r.querySelector(".edit").onclick=function(){openEditor(i)};r.querySelector(".copy").onclick=function(){if(c.profiles.length>=8){alert(T.limit);return}var x=JSON.parse(JSON.stringify(p));x.name=unique((p.name+T.copySuffix).slice(0,20));x.protected=false;c.profiles.splice(i+1,0,x);openEditor(i+1)};r.querySelector(".up").onclick=function(){move(i,i-1)};r.querySelector(".down").onclick=function(){move(i,i+1)};r.querySelector(".del").onclick=function(){if(c.profiles.length===1){alert(T.last);return}if(!confirm(T.confirm))return;var selected=c.profiles[c.selected];c.profiles.splice(i,1);c.selected=c.profiles.indexOf(selected);if(c.selected<0)c.selected=Math.min(i,c.profiles.length-1);draw()};profiles.appendChild(r)})}'+
    'function safe(x){var d=document.createElement("div");d.textContent=x;return d.innerHTML}function move(a,b){if(b<0||b>=c.profiles.length)return;var selected=c.profiles[c.selected],x=c.profiles.splice(a,1)[0];c.profiles.splice(b,0,x);c.selected=c.profiles.indexOf(selected);draw()}'+
    'function option(value,label,selected,invalid){var o=document.createElement("option");o.value=value;o.textContent=label;o.selected=selected;if(invalid)o.className="invalid";return o}'+
    'function openEditor(i){editing=i;draft=JSON.parse(JSON.stringify(c.profiles[i]));overview.className="hidden";editor.className="";q("name").value=draft.name;var s=q("locus");s.innerHTML="";if(loc.indexOf(draft.locus)<0&&draft.locus)s.appendChild(option(draft.locus,"⚠ "+draft.locus,true,true));loc.forEach(function(n){s.appendChild(option(n,n,n===draft.locus,false))});if(!draft.locus)s.selectedIndex=-1;drawMetrics()}'+
    'function drawMetrics(){var box=q("metrics");box.innerHTML="";draft.metrics.forEach(function(m,i){var r=document.createElement("div");r.className="metric";var s=document.createElement("select");MN.forEach(function(n,j){s.appendChild(option(j+1,n,j+1===m,false))});s.onchange=function(){draft.metrics[i]=+this.value};r.appendChild(s);[["↑",i-1],["↓",i+1]].forEach(function(a){var b=document.createElement("button");b.textContent=a[0];b.onclick=function(){if(a[1]>=0&&a[1]<draft.metrics.length){var x=draft.metrics.splice(i,1)[0];draft.metrics.splice(a[1],0,x);drawMetrics()}};r.appendChild(b)});var d=document.createElement("button");d.textContent=T.remove;d.onclick=function(){if(draft.metrics.length>1){draft.metrics.splice(i,1);drawMetrics()}};r.appendChild(d);box.appendChild(r)})}'+
    'q("addMetric").onclick=function(){if(draft.metrics.length>=6)return;for(var i=1;i<=21;i++)if(draft.metrics.indexOf(i)<0){draft.metrics.push(i);break}drawMetrics()};q("editorCancel").onclick=function(){draft=null;editor.className="hidden";overview.className=""};q("editorDone").onclick=function(){draft.name=q("name").value;draft.locus=q("locus").value;var dup=c.profiles.some(function(p,i){return i!==editing&&p.name.toLowerCase()===draft.name.toLowerCase()});var seen={};var badMetrics=draft.metrics.some(function(m){if(seen[m])return true;seen[m]=1;return false});if(!draft.name.trim()||draft.name.length>20||loc.indexOf(draft.locus)<0||badMetrics||draft.metrics.length<1){alert(dup?T.duplicate:T.invalid);return}if(dup){alert(T.duplicate);return}draft.protected=false;c.profiles[editing]=draft;q("editorCancel").click();draw()};'+
    'q("add").onclick=function(){if(c.profiles.length>=8){alert(T.limit);return}c.profiles.push({name:unique(T.activity),locus:"",protected:false,metrics:[1,3]});openEditor(c.profiles.length-1)};q("save").onclick=function(){c.theme=q("theme").value;var names={};var bad=c.profiles.some(function(p){var k=p.name.toLowerCase();if(names[k]||loc.indexOf(p.locus)<0)return true;names[k]=1;return false});if(bad){alert(T.invalid);return}c.profiles.forEach(function(p){p.protected=false});closeConfig(JSON.stringify(c))};draw();';
  }
  var profiles=[],transfer=new Transfer(),pendingOpen=false,openTimer=null,profileState='unavailable',compatibilityError=false;
  function watchLanguage(){try{return locale(Pebble.getActiveWatchInfo().language);}catch(_){return 'en';}}
  function readCache(){try{var x=JSON.parse(localStorage.getItem(CACHE)||'null');if(x&&Array.isArray(x.names))return x.names;}catch(_){}return [];}
  function openSettings(){if(openTimer){clearTimeout(openTimer);openTimer=null;}pendingOpen=false;var cached=readCache();var names=profiles.length?profiles:cached;var state=compatibilityError?'incompatible':profiles.length?'fresh':cached.length?'stale':profileState;Pebble.openURL(page(parse(localStorage.getItem(CONFIG))||defaultsFor(watchLanguage()),names,watchLanguage(),state));}
  function requestProfiles(){var d={};d[K.v]=V;d[K.release]=RELEASE;d[K.type]=7;Pebble.sendAppMessage(d);}
  if(typeof Pebble!=='undefined'){
    Pebble.addEventListener('ready',function(){var c=parse(localStorage.getItem(CONFIG))||defaultsFor(watchLanguage());localStorage.setItem(CONFIG,serialize(c));send(c);requestProfiles();});
    Pebble.addEventListener('showConfiguration',function(){pendingOpen=true;requestProfiles();openSettings();});
    Pebble.addEventListener('webviewclosed',function(e){if(!e.response)return;try{var c=JSON.parse(decodeURIComponent(e.response));migrate(c);if(validate(c)){localStorage.setItem(CONFIG,serialize(c));send(c);}}catch(_){}});
    Pebble.addEventListener('appmessage',function(e){var p=e.payload;if(Number(incoming(p,K.type,'MESSAGE_TYPE'))!==6)return;if(incoming(p,K.release,'APP_VERSION')!==RELEASE){compatibilityError=true;if(pendingOpen)openSettings();return;}var payload=transfer.accept(p);if(payload===null)return;var list=profilePayload(payload);if(list===null)return;profiles=list;profileState=list.length?'fresh':Number(incoming(p,K.result,'RESULT'))===3?'empty':'unavailable';if(list.length)localStorage.setItem(CACHE,JSON.stringify({names:list,updated:Date.now()}));if(pendingOpen&&list.length)openSettings();});
  }
  if(typeof module!=='undefined')module.exports={defaults:defaults,defaultsFor:defaultsFor,locale:locale,validate:validate,serialize:serialize,parse:parse,migrate:migrate,add:add,remove:remove,rename:rename,move:move,page:page,Transfer:Transfer,profilePayload:profilePayload,chunks:chunks};
})(this);
