ARG GENERATED_IMAGE
FROM ${GENERATED_IMAGE}
COPY tools/podman/android-emulator-entrypoint.sh /android/sdk/trackglance-entrypoint.sh
RUN chmod 0755 /android/sdk/trackglance-entrypoint.sh
CMD ["/android/sdk/trackglance-entrypoint.sh"]
